version: '3.2'
services:
  mysql:
    container_name: meu-mysql
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    volumes:
      # - ./initdb:/docker-entrypoint-initdb.d
     - initdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
     
    ports:
      - 3307:3307
volumes:
  initdb: